### ISSUE TITLE
Setting existing cookies through `Set-Cookie` is redundant

### ISSUE THREAD

**Issue by carlossless** [thereactivestack/react-cookie#52] opened 2016-12-13 13:44 UTC
Hi,

Great library! After trying out the SSR functionality I noticed that the library could potentially ignore `Set-Cookie` header entries if the Cookie already came in with the request and is exactly the same as the one to be set.

Another thought I had was that it would probably make sense to ignore redundant `Set-Cookie` entries with the same name. Right now every cookie action results with a `Set-Cookie`, even if they are for a cookie with the same name.

**Comment by eXon** [comment] 2016-12-13 17:00
It looks like express doesn't optimize the Set-Cookie when sending the request. I'm not sure how we could fix that because we have no way to know when the request is sent. Any idea?

**Comment by eXon** [comment] 2016-12-13 17:01
Ignoring the next set cookies could be problematic if it changed. Maybe we could check the current cookie and we set it only if the value changed.

**Comment by carlossless** [comment] 2016-12-13 21:24
> It looks like express doesn't optimize the Set-Cookie when sending the request. I'm not sure how we could fix that because we have no way to know when the request is sent. Any idea?

My assumption was that we could just check `_rawCookie` if a value already exists before setting it to `_res.cookie(...)`.

> Ignoring the next set cookies could be problematic if it changed. Maybe we could check the current cookie and we set it only if the value changed.

Yes this is what I had in mind.

**Comment by eXon** [comment] 2017-03-21 01:04
I'm closing this because this is not a bug and the value of having this is not worth it in my opinion. If you think otherwise, I'll be glad to review a PR.

**Closed by eXon** 2017-03-21 01:04 UTC

**Comment by carlossless** [comment] 2017-03-21 09:16
Yep, this turned out not to be a big deal for us either, so I won't be making a PR in the near future. If anyone else needs this, please go ahead.

Cheers!
